# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zCpurlin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.label_2.setBaseSize(QtCore.QSize(150, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_box_source_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_source_type.setObjectName("combo_box_source_type")
        self.horizontalLayout_2.addWidget(self.combo_box_source_type)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setBaseSize(QtCore.QSize(150, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line_edit_oracle_file = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_oracle_file.setObjectName("line_edit_oracle_file")
        self.horizontalLayout_3.addWidget(self.line_edit_oracle_file)
        self.push_button_select_oracle_file = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_select_oracle_file.setObjectName("push_button_select_oracle_file")
        self.horizontalLayout_3.addWidget(self.push_button_select_oracle_file)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setBaseSize(QtCore.QSize(150, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_edit_source_dir = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_source_dir.setObjectName("line_edit_source_dir")
        self.horizontalLayout_4.addWidget(self.line_edit_source_dir)
        self.push_button_source_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_source_dir.setObjectName("push_button_source_dir")
        self.horizontalLayout_4.addWidget(self.push_button_source_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setBaseSize(QtCore.QSize(150, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.line_edit_dist_dir = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_dist_dir.setObjectName("line_edit_dist_dir")
        self.horizontalLayout_5.addWidget(self.line_edit_dist_dir)
        self.push_button_dist_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_dist_dir.setObjectName("push_button_dist_dir")
        self.horizontalLayout_5.addWidget(self.push_button_dist_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.push_button_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_exit.setObjectName("push_button_exit")
        self.horizontalLayout_6.addWidget(self.push_button_exit)
        self.push_button_run = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_run.setObjectName("push_button_run")
        self.horizontalLayout_6.addWidget(self.push_button_run)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "zCpurlin"))
        self.label_2.setText(_translate("MainWindow", "选择数据源:"))
        self.label_3.setText(_translate("MainWindow", "Oracle清单文件:"))
        self.push_button_select_oracle_file.setText(_translate("MainWindow", "浏览"))
        self.label_4.setText(_translate("MainWindow", "数据源目录:"))
        self.push_button_source_dir.setText(_translate("MainWindow", "浏览"))
        self.label_5.setText(_translate("MainWindow", "目标目录:"))
        self.push_button_dist_dir.setText(_translate("MainWindow", "浏览"))
        self.push_button_exit.setText(_translate("MainWindow", "Exit"))
        self.push_button_run.setText(_translate("MainWindow", "Run"))
