# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zSplitting.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zSplitting(object):
    def setupUi(self, zSplitting):
        zSplitting.setObjectName("zSplitting")
        zSplitting.resize(1121, 803)
        self.centralwidget = QtWidgets.QWidget(zSplitting)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1121, 741))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.group_box_org = QtWidgets.QGroupBox(self.widget)
        self.group_box_org.setMinimumSize(QtCore.QSize(0, 50))
        self.group_box_org.setBaseSize(QtCore.QSize(50, 50))
        self.group_box_org.setObjectName("group_box_org")
        self.widget1 = QtWidgets.QWidget(self.group_box_org)
        self.widget1.setGeometry(QtCore.QRect(20, 30, 90, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_box_sjg = QtWidgets.QCheckBox(self.widget1)
        self.check_box_sjg.setObjectName("check_box_sjg")
        self.horizontalLayout_4.addWidget(self.check_box_sjg)
        self.check_box_lkq = QtWidgets.QCheckBox(self.widget1)
        self.check_box_lkq.setObjectName("check_box_lkq")
        self.horizontalLayout_4.addWidget(self.check_box_lkq)
        self.horizontalLayout_7.addWidget(self.group_box_org)
        self.group_box_catlog = QtWidgets.QGroupBox(self.widget)
        self.group_box_catlog.setObjectName("group_box_catlog")
        self.widget2 = QtWidgets.QWidget(self.group_box_catlog)
        self.widget2.setGeometry(QtCore.QRect(10, 30, 155, 18))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radio_button_zees = QtWidgets.QRadioButton(self.widget2)
        self.radio_button_zees.setObjectName("radio_button_zees")
        self.horizontalLayout_5.addWidget(self.radio_button_zees)
        self.radio_button_cees = QtWidgets.QRadioButton(self.widget2)
        self.radio_button_cees.setObjectName("radio_button_cees")
        self.horizontalLayout_5.addWidget(self.radio_button_cees)
        self.radio_button_trim = QtWidgets.QRadioButton(self.widget2)
        self.radio_button_trim.setObjectName("radio_button_trim")
        self.horizontalLayout_5.addWidget(self.radio_button_trim)
        self.horizontalLayout_7.addWidget(self.group_box_catlog)
        self.group_box_data_source = QtWidgets.QGroupBox(self.widget)
        self.group_box_data_source.setObjectName("group_box_data_source")
        self.widget3 = QtWidgets.QWidget(self.group_box_data_source)
        self.widget3.setGeometry(QtCore.QRect(10, 30, 186, 18))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radio_button_nc = QtWidgets.QRadioButton(self.widget3)
        self.radio_button_nc.setChecked(True)
        self.radio_button_nc.setObjectName("radio_button_nc")
        self.horizontalLayout_6.addWidget(self.radio_button_nc)
        self.radio_button_csv = QtWidgets.QRadioButton(self.widget3)
        self.radio_button_csv.setObjectName("radio_button_csv")
        self.horizontalLayout_6.addWidget(self.radio_button_csv)
        self.horizontalLayout_7.addWidget(self.group_box_data_source)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.combo_box_workcenter = QtWidgets.QComboBox(self.widget)
        self.combo_box_workcenter.setObjectName("combo_box_workcenter")
        self.horizontalLayout_3.addWidget(self.combo_box_workcenter)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tree_widget = QtWidgets.QTreeWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setMinimumSize(QtCore.QSize(800, 0))
        self.tree_widget.setBaseSize(QtCore.QSize(500, 0))
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.tree_widget)
        self.tree_view = QtWidgets.QTreeView(self.widget)
        self.tree_view.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_view.sizePolicy().hasHeightForWidth())
        self.tree_view.setSizePolicy(sizePolicy)
        self.tree_view.setObjectName("tree_view")
        self.horizontalLayout.addWidget(self.tree_view)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.push_button_load = QtWidgets.QPushButton(self.widget)
        self.push_button_load.setObjectName("push_button_load")
        self.horizontalLayout_2.addWidget(self.push_button_load)
        self.push_button_get = QtWidgets.QPushButton(self.widget)
        self.push_button_get.setObjectName("push_button_get")
        self.horizontalLayout_2.addWidget(self.push_button_get)
        self.push_button_transform = QtWidgets.QPushButton(self.widget)
        self.push_button_transform.setObjectName("push_button_transform")
        self.horizontalLayout_2.addWidget(self.push_button_transform)
        self.push_button_complete = QtWidgets.QPushButton(self.widget)
        self.push_button_complete.setObjectName("push_button_complete")
        self.horizontalLayout_2.addWidget(self.push_button_complete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        zSplitting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(zSplitting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 23))
        self.menubar.setObjectName("menubar")
        zSplitting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(zSplitting)
        self.statusbar.setObjectName("statusbar")
        zSplitting.setStatusBar(self.statusbar)
        self.tool_bar = QtWidgets.QToolBar(zSplitting)
        self.tool_bar.setObjectName("tool_bar")
        zSplitting.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)

        self.retranslateUi(zSplitting)
        QtCore.QMetaObject.connectSlotsByName(zSplitting)

    def retranslateUi(self, zSplitting):
        _translate = QtCore.QCoreApplication.translate
        zSplitting.setWindowTitle(_translate("zSplitting", "MainWindow"))
        self.group_box_org.setTitle(_translate("zSplitting", "ORG"))
        self.check_box_sjg.setText(_translate("zSplitting", "SJG"))
        self.check_box_lkq.setText(_translate("zSplitting", "LKQ"))
        self.group_box_catlog.setTitle(_translate("zSplitting", "Catlog"))
        self.radio_button_zees.setText(_translate("zSplitting", "Zees"))
        self.radio_button_cees.setText(_translate("zSplitting", "Cees"))
        self.radio_button_trim.setText(_translate("zSplitting", "Trim"))
        self.group_box_data_source.setTitle(_translate("zSplitting", "Data Source"))
        self.radio_button_nc.setText(_translate("zSplitting", "NC"))
        self.radio_button_csv.setText(_translate("zSplitting", "CSV LYSGHT"))
        self.label.setText(_translate("zSplitting", "WorkCenter:"))
        self.push_button_load.setText(_translate("zSplitting", "加载数据"))
        self.push_button_get.setText(_translate("zSplitting", "获取数据"))
        self.push_button_transform.setText(_translate("zSplitting", "转换数据"))
        self.push_button_complete.setText(_translate("zSplitting", "完工"))
        self.tool_bar.setWindowTitle(_translate("zSplitting", "toolBar"))
