# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zTransform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_zTransform(object):
    def setupUi(self, zTransform):
        zTransform.setObjectName("zTransform")
        zTransform.resize(822, 347)
        self.centralwidget = QtWidgets.QWidget(zTransform)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 90, 801, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 50))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_5.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.combo_box_data_source = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combo_box_data_source.setObjectName("combo_box_data_source")
        self.horizontalLayout_10.addWidget(self.combo_box_data_source)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(100, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.combo_box_dist_machine = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combo_box_dist_machine.setObjectName("combo_box_dist_machine")
        self.horizontalLayout_10.addWidget(self.combo_box_dist_machine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 50))
        self.label_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_6.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_source_folder = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_source_folder.setObjectName("lineEdit_source_folder")
        self.horizontalLayout_9.addWidget(self.lineEdit_source_folder)
        self.push_button_source_folder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_button_source_folder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.push_button_source_folder.setBaseSize(QtCore.QSize(50, 0))
        self.push_button_source_folder.setObjectName("push_button_source_folder")
        self.horizontalLayout_9.addWidget(self.push_button_source_folder)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 50))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_7.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_dist_folder = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_dist_folder.setObjectName("lineEdit_dist_folder")
        self.horizontalLayout_8.addWidget(self.lineEdit_dist_folder)
        self.push_botton_dist_folder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_botton_dist_folder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.push_botton_dist_folder.setBaseSize(QtCore.QSize(50, 0))
        self.push_botton_dist_folder.setObjectName("push_botton_dist_folder")
        self.horizontalLayout_8.addWidget(self.push_botton_dist_folder)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.push_button_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_button_start.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_start.setFont(font)
        self.push_button_start.setObjectName("push_button_start")
        self.horizontalLayout_2.addWidget(self.push_button_start, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 250, 801, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        zTransform.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(zTransform)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 23))
        self.menubar.setObjectName("menubar")
        zTransform.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(zTransform)
        self.statusbar.setObjectName("statusbar")
        zTransform.setStatusBar(self.statusbar)

        self.retranslateUi(zTransform)
        # self.push_button_source_folder.clicked.connect(zTransform.on_pushButton_clicked)
        QtCore.QMetaObject.connectSlotsByName(zTransform)

    def retranslateUi(self, zTransform):
        _translate = QtCore.QCoreApplication.translate
        zTransform.setWindowTitle(_translate("zTransform", "zTransform"))
        self.label.setText(_translate("zTransform", "zTransform"))
        self.label_4.setText(_translate("zTransform", "Transform Desinge Data to MFG code"))
        self.label_5.setText(_translate("zTransform", "数据源："))
        self.label_8.setText(_translate("zTransform", "目标机器："))
        self.label_6.setText(_translate("zTransform", "源目录："))
        self.push_button_source_folder.setText(_translate("zTransform", "浏览"))
        self.label_7.setText(_translate("zTransform", "目的目录："))
        self.push_botton_dist_folder.setText(_translate("zTransform", "浏览"))
        self.push_button_start.setText(_translate("zTransform", "开始"))
        self.label_3.setText(_translate("zTransform", "Programed by: Zhan, Yongqiang"))
        self.label_2.setText(_translate("zTransform", "Verson: Beta"))
        self.label_9.setText(_translate("zTransform", "Date:2019.3.12"))

