__author__ = "zanweb <zanweb@163.com>"

# DTR HOLE X_REFERENCE
LEADING_EDGE = 0
TRAILING_EDGE = 1
LEADING_CENTER = 2
TRAILING_CENTER = 3
EVEN_SPACE = 4
SPACING_LIMIT = 5
KERF_ADJUST = 8

# DTR HOLE Y_REFERENCE
CENTER_P = 1
CENTER_N = 2
EDGE_P = 3
EDGE_N = 4
MACRO_P = 5
MACRO_N = 6

# MM AND INCH TRANS
MM_INCH = 25.4
